# Generated by Django 3.1 on 2020-08-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=8)),
                ('dob', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='media/')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
