# Generated by Django 3.1 on 2020-09-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveller',
            name='dob',
        ),
        migrations.AlterField(
            model_name='traveller',
            name='image',
            field=models.ImageField(upload_to='traveller_pics'),
        ),
    ]
