# Generated by Django 3.1.1 on 2020-09-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20200904_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='image',
            field=models.ImageField(upload_to='traveller_pics/'),
        ),
    ]
