# Generated by Django 3.1.1 on 2020-09-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_traveller_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='dob',
            field=models.CharField(max_length=30),
        ),
    ]
